# Generated by Django 4.1.2 on 2022-10-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('User_name', models.CharField(max_length=50)),
                ('User_email', models.CharField(max_length=50)),
                ('User_mobile', models.IntegerField()),
            ],
        ),
    ]
