# Generated by Django 4.1.1 on 2022-10-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirstapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='str_image')),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
