# Generated by Django 4.1.1 on 2022-10-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirstapp', '0003_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='descriptions',
            field=models.CharField(max_length=50),
        ),
    ]
