# Generated by Django 4.1.1 on 2022-11-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirstapp', '0004_alter_store_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('offeredsalary', models.IntegerField()),
                ('qualification', models.CharField(max_length=150)),
            ],
        ),
    ]
