# Generated by Django 4.1.1 on 2022-11-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirstapp', '0006_alter_job_posting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100)),
            ],
        ),
    ]
