# Generated by Django 4.1.1 on 2022-11-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_coach_register_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach_register',
        ),
    ]
