# Generated by Django 4.1.1 on 2022-11-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach_register',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach_register',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
