# Generated by Django 4.1.1 on 2022-11-20 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Coach', '0005_coach_register_email_coach_register_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach_register',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
