# Generated by Django 4.1.1 on 2022-10-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=50)),
                ('MotherName', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('EmailId', models.EmailField(max_length=254)),
                ('Educations', models.CharField(max_length=250)),
                ('Experience', models.CharField(max_length=300)),
                ('Hobbies', models.CharField(max_length=100)),
                ('Skill', models.CharField(max_length=100)),
                ('Descripiton', models.CharField(max_length=500)),
            ],
        ),
    ]
