# Generated by Django 4.1.1 on 2022-11-23 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('sport', models.CharField(max_length=100)),
                ('disability', models.CharField(max_length=30)),
                ('height', models.FloatField()),
                ('Experience', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
