# Generated by Django 4.1.1 on 2022-11-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_register',
            name='Experience',
        ),
    ]
